Database aggiornato da me e enrico
VoltDevelopers/Simulation-lotto pull request #25
Opened 2022-03-09 18:27 UTC by drbrx

Chiederei a chi è direttamente interessato di dare un'occhiata. Manca ancora tutto ciò che ha a cahe afre con il log ma non è di nostra competenza (credo, se lo è fateci sapere). Tra le modifiche ci sono alcune a Settings, che ora contiene delle costanti per cose come "quanti numeri ci sono nel lotto", "quanti numeri si estraggono per round" e simili, che credo sarebbe bene utilizzaste. Per qualsiasi necessità o modifica fatemi(ci) sapere pure

2022-03-09 18:57 UTC, WlanKasper commented on Lotto/.floo
> +{
To Delete

2022-03-09 18:57 UTC, WlanKasper commented on Lotto/.flooignore
> +extern
To Delete

2022-03-09 18:59 UTC, WlanKasper commented on Lotto/app/src/main/java/com/voltdevelopers/lotto/data/Database.java
> +    public int[] getNMostFrequent(int nRequested){
Non serve il parametro, perche il numero di estrazioni si decide una volta al inizio

2022-03-09 19:00 UTC, WlanKasper commented on Lotto/app/src/main/java/com/voltdevelopers/lotto/data/Database.java
> +    public int[] getLatestN(int nRequested){
Non serve il parametro, perche il numero di estrazioni si decide una volta al inizio

2022-03-09 19:00 UTC, WlanKasper commented on Lotto/app/src/main/java/com/voltdevelopers/lotto/data/Database.java
> +    public int[] getOldestN(int nRequested){
Non serve il parametro, perche il numero di estrazioni si decide una volta al inizio

2022-03-09 19:00 UTC, WlanKasper commented on Lotto/app/src/main/java/com/voltdevelopers/lotto/data/Profile.java
>  public class Profile {
Si puo' fare come una classe interna di db

2022-03-09 19:01 UTC, WlanKasper commented on Lotto/app/src/main/java/com/voltdevelopers/lotto/data/Settings.java
> +    public static final int NUMBERS_X_EXTRACTION = 5;
Puo' variarsi da 1 a 5

2022-03-09 19:04 UTC, WlanKasper requested changes
Vi consiglio di guardare il mio pull, ho cambiato un'po la classe

Secondo me il db deve solo contenere i dati necesari con un semplice inserimento e invio.

2022-03-10 16:10 UTC, drbrx commented on Lotto/app/src/main/java/com/voltdevelopers/lotto/data/Database.java
> +    public int[] getNMostFrequent(int nRequested){
Ho messo nel caso qualcuno volesse usare per altro la classe, tipo per la ui. al massimo si può passare 1 comunque. Se serve posso overloadare e mettere uno senza parametri che chiama con parametro "1"

2022-03-10 16:12 UTC, drbrx commented on Lotto/app/src/main/java/com/voltdevelopers/lotto/data/Settings.java
> +    public static final int NUMBERS_X_EXTRACTION = 5;
NUMBERS_X_EXTRACTION no, se ti riferisci a N_PLAYERS allora non credo no, ma posso sempre togliere final e mettere get/set

2022-03-10 16:13 UTC, drbrx commented on Lotto/app/src/main/java/com/voltdevelopers/lotto/data/Settings.java
> +    public static final String[] PLAYER_NAMES = {"Il Copione", "Il Ritardatario", "L' Azzardoso", "Il Testardo", "L' Ingenuo"};
ma è solo la lista, poi vengono assegnati ai profile

2022-03-10 18:11 UTC, WlanKasper approved these changes

2022-03-10 18:11 UTC, merged